language: scala
scala:
- 2.10.5
- 2.11.5
sudo: required
cache:
  directories:
  - "$HOME/.ivy2/cache"
services:
- docker
before_install:
# TZ needed for Oracle driver!
- export TZ=Asia/Kamchatka
- sh -v ZNonPublicDeps/install
- docker version
- sh -v travis/runcontainer.sh oracle
- sh -v travis/runcontainer.sh db2
- docker ps
script:
- sbt ++$TRAVIS_SCALA_VERSION 'set javaOptions ++= Seq("-Dslick.testkit-config=test-dbs/testkit-travis.conf")' clean test +it:test && sbt ++$TRAVIS_SCALA_VERSION 'set javaOptions ++= Seq("-Dslick.testkit-config=test-dbs/testkit-travis.conf")' clean coverage test it:test
after_success:
# coveralls can't combine travis and appveyor build yet
#- sbt ++$TRAVIS_SCALA_VERSION coveralls
- sbt ++$TRAVIS_SCALA_VERSION +publishMasterOnTravis
env:
  global:
    secure: Ouzwf4vUPDvMqiSaLDo0PHYRADPjGPlYOAnkKbnAuzrNBJ98TKRuDP2zopQ95JpSxiKdOxX6GCmpJOAqCEQaXyYZZ6XbHijjDcVNJf9aTJf09msHiMEOhxpxn08rf9viUi/as+jq+/ngj6L7N23aiRZDJHcpXGEecWbd6eeKgl4=
    secure: "VcT5n6mJcGdHLl3GgcCt08+CG6eOfKeG+t6zOLBwY3CS0jE3hiqT48/eedOJZEXwxcQ6p/dXBQg+HuR/DkSxlyNt09JBrbUYs6VHZAftHypt6x4bb+J/5oVgohbcGXVyOgywRwsZrz0sjtfxeijT/HYa66EGoDCD4zUkSdAIN/8="
    secure: "VWN4NkrEFf9dZw7b8mW1aUVc+WzBdQq3ZXwaLK5Ap5T+tyvNxij5zt6NvQphu6TyFq/jfX0LCHVOf/chuydqqMcyz/iXJPQSPFFZ7YGZV0GEWmt/2pw2CKrVsDsp52KUqYKFCfbgNX4DTuIVJaujXktMgJRkOpSKZP7LKtAIxtk="

